### ISSUE TITLE
Seems non working on latest certbot

### ISSUE THREAD

**Issue by Jayd603** [cybercinch/certbot-dns-directadmin#11]
root@s3:~# certbot certonly --authenticator dns-directadmin -d *.s3.XXXXX.net
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for *.s3.XXXX.net
Input the path to your DirectAdmin credentials INI file (Enter 'c' to cancel): da.ini
Encountered exception during recovery: ValueError: bad query field: ''
An unexpected error occurred:
ValueError: bad query field: ''

docs are wrong on ini file variables too:
the command line options don't work and if i omit them i get prompted but then..
{}: dns_directadmin_username (Username) and  dns_directadmin_password (Password)
or dns_directadmin_token (Access Token) are required

Fixed those but then the above error happens. Maybe because of my wildcard subdomain cert, i didnt try anything else.

**Comment by guisea** [comment]
Hi,  this has been test against Certbot 2.9.0 and works fine.  A new release has been made to support issuing certs against a pointer domain.   

See commentary in #14
