### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by raczkow** [cybercinch/certbot-dns-directadmin#2]
Hi,
There is a mistake pointing to:
`--certbot-dns-directadmin:panel-credentials /path/to/directadmin-credentials.ini`
instead of:
`--certbot-dns-directadmin:directadmin-credentials /path/to/directadmin-credentials.ini`
in README

Took a while to get it work because of that.

**Comment by guisea** [comment]
Thanks,   documentation was moved to Read The Docs, without that slight documentation hiccup.  I have updated now with a pointer to Read The Docs documentation.

**Comment by slokhorst** [comment]
Please note that the first code block in the `3. Run` section on the [PyPI page](https://pypi.org/project/certbot-dns-directadmin/) also still mentions `certbot-dns-directadmin:panel-credentials`.

**Comment by guisea** [comment]
Thanks,

I will check it out.  Will have to push a new version to fix that I think.
