### ISSUE TITLE
Latest versions not on PyPi

### ISSUE THREAD

**Issue by bobvandevijver** [cybercinch/certbot-dns-directadmin#30]
See https://pypi.org/project/certbot-dns-directadmin/#history, 1.0.7 and higher are missing. Curious whether those release would solve the issue that seem to have started with 1.0.5 (see #26).

**Comment by 0xFelix** [comment]
Ping @guisea 

I saw the same behavior, latest version on PyPi is 1.0.6

**Comment by guisea** [comment]
@bobvandevijver @0xFelix 

Odd,  I will investigate why later releases have not made it to PyPI.  

Have quite a bit on at the moment but will try find some time to look into it.

**Comment by guisea** [comment]
@0xFelix @bobvandevijver 

I have sorted things.  Applied all dependency updates so should be in a much more compatible space.  All tests passing.

**Comment by guisea** [comment]
Updated docker container and manually asserted latest version from PyPi is installed.  #26 was probably causing trouble but has now been resolved.
