### ISSUE TITLE
acme dependency should be updated to acme>=2.11.0

### ISSUE THREAD

**Issue by 0xFelix** [cybercinch/certbot-dns-directadmin#32]
To be compatible with the latest certbot PyPi packages, this package's dependency on `acme` should be raised to `>=2.11.0`.

**Comment by guisea** [comment]
Dependencies are updated now @0xFelix 

New release is published to pypi

**Comment by 0xFelix** [comment]
@guisea Thanks a lot for taking care of it!

**Comment by 0xFelix** [comment]
@guisea Sorry to bother you again.

`certbot = "^3.0.1"` causes a new problem. Do you think this requirement could be lowered to `>=2.11.0`?

See https://github.com/home-assistant/addons/actions/runs/11988068375/job/33426570042#step:7:710

**Comment by guisea** [comment]
Sure, I have made a change to project dependencies. New package has been released today.   

This also includes fix for #26 

> @guisea Sorry to bother you again.
> 
> `certbot = "^3.0.1"` causes a new problem. Do you think this requirement could be lowered to `>=2.11.0`?
> 
> See https://github.com/home-assistant/addons/actions/runs/11988068375/job/33426570042#step:7:710
