### ISSUE TITLE
certbot 1.8/1.9 compatibility

### ISSUE THREAD

**Issue by syserr0r** [cybercinch/certbot-dns-directadmin#4]
The current version breaks certbot and does not provide a clear error message if this package is installed after installing certbot (note that pip **does** mention this incompatibility)

Certbot fails to launch due to requirements <1.8 but installed package 1.9 but does not mention which package is causing this.

An improvement might be not to constrain max version but detect higher versions than supported and print a warning message, including the package name?

**Comment by guisea** [comment]
I have reverted the restriction on certbot requirement back in version 0.0.21.  Is no longer an issue
